[package]
name = "local-minecraft-room-desktop"
version = "0.0.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
